# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('money', models.IntegerField(blank=True, null=True, verbose_name='Amount of Money')),
                ('blocked', models.IntegerField(blank=True, null=True, verbose_name='Blocked Money')),
                ('kind', models.CharField(max_length=100, verbose_name='Type of Account')),
            ],
            options={
                'verbose_name': ('Bank Account',),
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Month Name')),
            ],
            options={
                'verbose_name': 'month',
                'verbose_name_plural': 'months',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Money Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account', verbose_name='Bank Account')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Month', verbose_name='Month')),
            ],
            options={
                'verbose_name': 'Belance',
                'verbose_name_plural': 'Belances',
            },
        ),
    ]
