# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date of Month'),
        ),
    ]
