# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('cash', '\u0413\u043e\u0442\u0456\u0432\u043a\u0430'), ('bank', '\u0411\u0430\u043d\u043a')], max_length=100, verbose_name='Type of Account'),
        ),
    ]
