# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180519_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Money Amount'),
        ),
    ]
