# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-27 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_month_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionToAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Transaction Amount')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Transaction Time')),
                ('detail', models.CharField(blank=True, max_length=256, null=True, verbose_name='Detail Info')),
                ('account_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account', verbose_name='Transaction Source')),
            ],
            options={
                'verbose_name': 'Plus-Transaction',
                'verbose_name_plural': 'Plus-Transactions',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Transaction Time'),
        ),
    ]
