# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_month_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Money Amount'),
        ),
    ]
