# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-10 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_accounttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Money Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Saving',
                'verbose_name_plural': 'Savings',
            },
        ),
        migrations.CreateModel(
            name='SavingTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('total_amount', models.IntegerField(blank=True, null=True, verbose_name='Total amount of money')),
            ],
            options={
                'verbose_name': 'Total Saving',
                'verbose_name_plural': 'Total Savings',
            },
        ),
        migrations.AddField(
            model_name='saving',
            name='saving_total',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.SavingTotal', verbose_name='Total Saving'),
        ),
    ]
