# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20180521_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Money Amount')),
                ('detail', models.CharField(blank=True, max_length=256, null=True, verbose_name='Detail Info')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account', verbose_name='Bank Account')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Month', verbose_name='Month')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='PlannedExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Money Amount')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Month', verbose_name='Month')),
            ],
            options={
                'verbose_name': 'Planned Expense',
                'verbose_name_plural': 'Planned Expenses',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.PlannedExpense', verbose_name='Planned Expense'),
        ),
    ]
