# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-28 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20181010_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Transaction Amount')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Transaction Time')),
                ('detail', models.CharField(blank=True, max_length=256, null=True, verbose_name='Detail Info')),
            ],
            options={
                'verbose_name': 'Saving Transaction',
                'verbose_name_plural': 'Saving Transactions',
            },
        ),
        migrations.RemoveField(
            model_name='savingtotal',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='month',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='planned_expense',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='score_goal',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='score_goal_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='score_source',
        ),
        migrations.AddField(
            model_name='transaction',
            name='model',
            field=models.CharField(default='Nothing', max_length=256, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='transactiontoaccount',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Transaction', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Amount of Money'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Money Amount'),
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='saving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Saving', verbose_name='Saving'),
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Transaction', verbose_name='Transaction'),
        ),
    ]
