# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20180521_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='expenses_done',
            field=models.IntegerField(default=0, verbose_name='Amount of Done Expenses'),
        ),
        migrations.AddField(
            model_name='month',
            name='expenses_plan',
            field=models.IntegerField(default=0, verbose_name='Amount of Planned Expenses'),
        ),
    ]
