# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-27 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20180521_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='approved',
            field=models.NullBooleanField(verbose_name='State of Affirmation'),
        ),
    ]
