# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20180528_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Transaction Time'),
        ),
    ]
