# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20180601_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='remainder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Money Remainder'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Transaction Time'),
        ),
    ]
