# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20180601_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='score_goal_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Transaction Goal Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='score_goal',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Transaction Goal Id'),
        ),
    ]
